# # Continuous Integration workflow: Lint & Test on every push / PR

# name: CI

# on:
#   push:
#     branches: ["**"]
#   pull_request:

# jobs:
#   js-tests:
#     name: "JS / Hardhat Tests"
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Use Node.js 18
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: "npm"

#       - name: Install dependencies
#         run: npm ci

#       - name: Run Hardhat tests
#         run: npm test --if-present

#   python-lint:
#     name: "Python Lint & (optional) PyTests"
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Python 3.10
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
#           cache: "pip"

#       - name: Install dependencies
#         run: |
#           pip install --upgrade pip
#           pip install -r requirements.txt ruff

#       - name: Run Ruff linter (fast, opinionated)
#         run: ruff ai_service --output-format=github

#       - name: Run PyTest (if tests exist)
#         run: |
#           python -m pytest || echo "No Python tests found – skipping"
